- name: Generate values files
  hosts: localhost
  connection: local
  gather_facts: false

  tasks:
    - name: Handle each environment
      include_tasks: environment_tasks.yml
      loop:
        - dev
        - staging
        - prod
      vars:
        env: "{{ item }}"

    - name: Update Chart.yaml
      template:
        src: templates/Chart.yaml.j2
        dest: ../charts/cicd-flask/Chart.yaml
