# change the replica count to 3 here
replicaCount: 3
image:
  repository: xiFueL/ci-cd-with-argocd-helm-and-github-actions
  pullPolicy: IfNotPresent
  tag: "latest"
imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""
serviceAccount:
  create: true
  annotations: {}
  name: ""
service:
  type: ClusterIP
  port: 5000
ingress:
  enabled: true
  className: ""
  annotations:
    kubernetes.io/ingress.class: nginx
  hosts:
    - host: flask.144.126.246.47.nip.io
      paths:
        - path: /tasks
          pathType: Prefix
  tls: []
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
